name = "my-cf-api"
type = "javascript"
account_id = "19510eada67ada2e5ac85032049cc468"
# entry-point = "build"
# prepare_script = "prepare-worker"
workers_dev = true
compatibility_date = "2022-06-05"

kv_namespaces = [ 
         { binding = "VENTRATA", id= "4efeb9184bc4434fbe1b5431fda143d2" ,  preview_id = "df1bf1ca3d9249598935e4ceaf9aa774" }
]

[build]
command = "npm install && npm run build"

[build.upload]
format = "service-worker"